DATA_DIR = "src/data"
ANCESTRY_FILE = f"""{DATA_DIR}/ancestries.json"""
BACKGROUND_FILE = f"""{DATA_DIR}/backgrounds.json"""
CHARACTER_FILE = f"""{DATA_DIR}/characters.json"""
DATA_KEY = "data"
INFO_KEY = "info"
ID_KEY = "id"